/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lenovo_dingjq1_myndkapplication_JNItest */

#ifndef _Included_com_lenovo_dingjq1_myndkapplication_JNItest
#define _Included_com_lenovo_dingjq1_myndkapplication_JNItest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lenovo_dingjq1_myndkapplication_JNItest
 * Method:    getStringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lenovo_dingjq1_myndkapplication_JNItest_getStringFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
